server {
    listen 80;

    # ---------- AUTH SERVICE ----------
    location /auth/ {
        proxy_pass http://auth:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ---------- TOKEN VALIDATION ----------
    location = /auth/verify {
        internal;
        proxy_pass http://auth:5001/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
    }

    # # ---------- CONTENT ----------
    # location /content/ {
    #     auth_request /auth/verify;
    #     proxy_pass http://content:5002/;
    # }

    # # ---------- CODE ----------
    # location /code/ {
    #     auth_request /auth/verify;
    #     proxy_pass http://code:5003/;
    # }

    # # ---------- PROCTOR ----------
    # location /proctor/ {
    #     auth_request /auth/verify;
    #     proxy_pass http://proctor:5004/;
    # }
}